@startuml
partition Lab Asset Manager{
    start
    if ("Select Action") then (View documents)
        :Get list of assets;
        if ("Select asset to view its document") then (Document Selected)
        fork
            :Get asset name;
        fork again
            :Get Document type (manuals, warranties, calibration/maintenance logs);
        fork again
            :Get name of who uploaded said document;
        fork again
            :Get date and timestamp of when document was uploaded;
        end fork
        endif
    else (Upload Documents)
        :Ask for document file location to upload;
        partition Documents{
            :Receive file;
            :Check file type;
            if (Is file type a PDF?) then (valid)
                :Upload document to documents folder;
                fork
                    :Record timestamp in UTC;
                fork again
                    :Record Uploader;
                fork again
                    :Record document type;
                end fork
                :Attach all recorded metadata to file;
            else (invalid)
                :Send invalid file type error to uploader;
            endif
        }
    endif
stop
}
@enduml